# Generated by Django 5.0.6 on 2025-01-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Sobrenome')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('birth_date', models.DateField(max_length=100, verbose_name='Data de Nascimento')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Funcionário'), ('user', 'Usuário')], default='user', max_length=10, verbose_name='Cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuário Interno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'accounts_user',
            },
        ),
    ]
