# Generated by Django 5.0.6 on 2024-11-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_default_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Funcionário'), ('user', 'Usuário')], default='user', max_length=10, verbose_name='Função'),
        ),
    ]
