# Generated by Django 5.0.6 on 2024-11-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Funcionário'), ('user', 'Usuário')], default='user', max_length=10, verbose_name='Cargo'),
        ),
    ]
