services:
  db:
    image: postgis/postgis:latest 
    container_name: ipici_postgres
    environment:
      POSTGRES_USER: ipici
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ipici
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init_postgis.sql:/docker-entrypoint-initdb.d/init_postgis.sql 

  adminer:
    image: adminer
    container_name: ipici_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  mailhog:
    container_name: ipici-mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  ipici-api:
    container_name: ipici-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: './scripts/start-api.sh'
    volumes:
      - ./backend/:/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-whg8eyrugweryu83845438977gh
      - ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.13
      - BASE_URL=http://localhost:8000
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=ipici
      - DATABASE_USERNAME=ipici
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=False
      - EMAIL_USE_SSL=False
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - DEFAULT_FROM_EMAIL=webmaster@localhost
      - EMAIL_LOCAL_HOST=http://mailhog
    depends_on:
      - db