# Generated by Django 5.0.6 on 2025-01-02 21:35

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('recipient_list', models.TextField(verbose_name='Destinatários')),
                ('html_message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('plain_message', models.TextField(blank=True, null=True, verbose_name='Mensagem (Texto)')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enviado em')),
                ('success', models.BooleanField(default=False, verbose_name='Enviado com Sucesso')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
            ],
            options={
                'verbose_name': 'Histórico de E-mail',
                'verbose_name_plural': 'Histórico de E-mails',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão')], max_length=10, verbose_name='Ação')),
                ('object_id', models.CharField(max_length=255, verbose_name='ID do Objeto')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Representação do Objeto')),
                ('changes', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Alterações')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'ordering': ['-timestamp'],
            },
        ),
    ]
