# Generated by Django 4.2.13 on 2024-10-27 16:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('TECNICO', 'Técnico'), ('ADMINISTRADOR', 'Administrador'), ('CIDADAO', 'Cidadão')], max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuario_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoIluminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('proprietario', models.CharField(max_length=100)),
                ('denominacao_estrutural', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('LUMINARIA', 'Luminária'), ('POSTE', 'Poste')], max_length=50)),
                ('altura', models.FloatField()),
                ('material', models.CharField(max_length=100)),
                ('data_instalacao', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status_operacional', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('MANUTENCAO', 'Em Manutenção'), ('FALHA', 'Falha Detectada')], max_length=50)),
                ('codigo_qr', models.CharField(max_length=100, unique=True)),
                ('fonte_energia', models.CharField(max_length=100)),
                ('recursos_adicionais', models.TextField(blank=True, null=True)),
                ('instalacoes_proximas', models.TextField(blank=True, null=True)),
                ('data_ultima_manutencao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('coordenadas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_sensor', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('FALHA_DETECTADA', 'Falha Detectada'), ('INATIVO', 'Inativo')], max_length=50)),
                ('data_ultimo_relatorio', models.DateTimeField()),
                ('tipo_conexao', models.CharField(choices=[('WIFI', 'Wi-Fi'), ('LORAWAN', 'LoRaWAN'), ('LORA_MESH', 'LoRa Mesh')], max_length=50)),
                ('versao_firmware', models.CharField(max_length=50)),
                ('nivel_bateria', models.FloatField(blank=True, null=True)),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='core.dispositivoiluminacao')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaRelatado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_relato', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='problemas/')),
                ('status', models.CharField(choices=[('RELATADO', 'Relatado'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido')], max_length=15)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='core.dispositivoiluminacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_reportados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('prioridade', models.CharField(choices=[('ALTA', 'Alta'), ('BAIXA', 'Baixa')], max_length=5)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], max_length=15)),
                ('imagem_dispositivo', models.ImageField(blank=True, null=True, upload_to='ordens/')),
                ('tipo_problema', models.CharField(max_length=100)),
                ('origem', models.CharField(choices=[('CIDADAO', 'Cidadão'), ('SENSOR', 'Sensor'), ('ADMINISTRADOR', 'Administrador')], max_length=15)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_autor', to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='core.dispositivoiluminacao')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateField()),
                ('descricao', models.TextField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='core.dispositivoiluminacao')),
                ('tecnico_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dispositivoiluminacao',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='core.zona'),
        ),
        migrations.CreateModel(
            name='CustoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_custo', models.CharField(choices=[('INSTALACAO', 'Instalação'), ('MANUTENCAO', 'Manutenção'), ('OPERACIONAL', 'Operacional')], max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='core.dispositivoiluminacao')),
            ],
        ),
    ]
