# Generated by Django 4.2.13 on 2024-11-02 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do País')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código do País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='LightingDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('owner', models.CharField(max_length=100, verbose_name='Proprietário')),
                ('structural_name', models.CharField(max_length=100, verbose_name='Denominação Estrutural')),
                ('type', models.CharField(choices=[('LUMINARIA', 'Luminária'), ('POSTE', 'Poste')], max_length=50, verbose_name='Tipo')),
                ('height', models.FloatField(verbose_name='Altura')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('installation_date', models.DateField(verbose_name='Data de Instalação')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('operational_status', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('MANUTENCAO', 'Em Manutenção'), ('FALHA', 'Falha Detectada')], max_length=50, verbose_name='Status Operacional')),
                ('qr_code', models.CharField(max_length=100, unique=True, verbose_name='Código QR')),
                ('energy_source', models.CharField(max_length=100, verbose_name='Fonte de Energia')),
                ('additional_features', models.TextField(blank=True, null=True, verbose_name='Recursos Adicionais')),
                ('nearby_installations', models.TextField(blank=True, null=True, verbose_name='Instalações Próximas')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Manutenção')),
            ],
            options={
                'verbose_name': 'Dispositivo de Iluminação',
                'verbose_name_plural': 'Dispositivos de Iluminação',
            },
        ),
        migrations.CreateModel(
            name='MailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('recipient_list', models.TextField(verbose_name='Destinatários')),
                ('html_message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('plain_message', models.TextField(blank=True, null=True, verbose_name='Mensagem (Texto)')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enviado em')),
                ('success', models.BooleanField(default=False, verbose_name='Enviado com Sucesso')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
            ],
            options={
                'verbose_name': 'Histórico de E-mail',
                'verbose_name_plural': 'Histórico de E-mails',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('coordinates', models.TextField(verbose_name='Coordenadas')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('priority', models.CharField(choices=[('ALTA', 'Alta'), ('BAIXA', 'Baixa')], max_length=5, verbose_name='Prioridade')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], max_length=15, verbose_name='Status')),
                ('device_image', models.ImageField(blank=True, null=True, upload_to='orders/', verbose_name='Imagem do Dispositivo')),
                ('problem_type', models.CharField(max_length=100, verbose_name='Tipo de Problema')),
                ('origin', models.CharField(choices=[('CIDADAO', 'Cidadão'), ('SENSOR', 'Sensor'), ('ADMINISTRADOR', 'Administrador')], max_length=15, verbose_name='Origem')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_author', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='core.lightingdevice', verbose_name='Dispositivo')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_status', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('FALHA_DETECTADA', 'Falha Detectada'), ('INATIVO', 'Inativo')], max_length=50, verbose_name='Status do Sensor')),
                ('last_report_date', models.DateTimeField(verbose_name='Data do Último Relatório')),
                ('connection_type', models.CharField(choices=[('WIFI', 'Wi-Fi'), ('LORAWAN', 'LoRaWAN'), ('LORA_MESH', 'LoRa Mesh')], max_length=50, verbose_name='Tipo de Conexão')),
                ('firmware_version', models.CharField(max_length=50, verbose_name='Versão do Firmware')),
                ('battery_level', models.FloatField(blank=True, null=True, verbose_name='Nível de Bateria')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='core.lightingdevice', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.CreateModel(
            name='ReportedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Relato')),
                ('image', models.ImageField(blank=True, null=True, upload_to='problems/', verbose_name='Imagem')),
                ('status', models.CharField(choices=[('RELATADO', 'Relatado'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido')], max_length=15, verbose_name='Status')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='core.lightingdevice', verbose_name='Dispositivo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_problems', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Problema Relatado',
                'verbose_name_plural': 'Problemas Relatados',
            },
        ),
        migrations.CreateModel(
            name='OperationalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('INSTALACAO', 'Instalação'), ('MANUTENCAO', 'Manutenção'), ('OPERACIONAL', 'Operacional')], max_length=15, verbose_name='Tipo de Custo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='core.lightingdevice', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Custo Operacional',
                'verbose_name_plural': 'Custos Operacionais',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Data de Manutenção')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.lightingdevice', verbose_name='Dispositivo')),
                ('responsible_technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
            },
        ),
        migrations.AddField(
            model_name='lightingdevice',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.zone', verbose_name='Zona'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Ação')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
            },
        ),
    ]
