# Generated by Django 5.0.6 on 2024-11-04 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='service_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='core.serviceorder', verbose_name='Ordem de Serviço'),
        ),
    ]
