# Generated by Django 5.0.6 on 2024-11-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='boundary_color',
            field=models.CharField(default='#3388ff', max_length=7, verbose_name='Cor da Zona'),
        ),
    ]
