# Generated by Django 5.0.6 on 2025-01-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightingdevice',
            name='energy_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Energia'),
        ),
        migrations.AlterField(
            model_name='lightingdevice',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='lightingdevice',
            name='structural_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Denominação Estrutural'),
        ),
    ]
