# Generated by Django 5.0.6 on 2025-01-03 00:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lightingdevice_energy_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localização'),
        ),
    ]
