# Generated by Django 5.0.6 on 2025-01-01 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'default_permissions': (), 'managed': False, 'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
    ]
