# Generated by Django 5.0.6 on 2024-11-07 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maintenance_service_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='origin',
        ),
        migrations.AddField(
            model_name='reportedproblem',
            name='origin',
            field=models.CharField(choices=[('CIDADAO', 'Cidadão'), ('SENSOR', 'Sensor'), ('ADMINISTRADOR', 'Administrador')], default='CIDADAO', max_length=15, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='reportedproblem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_problems', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
