# Generated by Django 5.0.6 on 2025-01-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_report_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='device_count',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='problem_count',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
    ]
