# Generated by Django 5.0.6 on 2024-12-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_serviceorder_origin_reportedproblem_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='operational_cost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance', to='core.operationalcost', verbose_name='Custo Operacional'),
        ),
        migrations.AlterField(
            model_name='reportedproblem',
            name='origin',
            field=models.CharField(choices=[('CIDADAO', 'Cidadão'), ('SENSOR', 'Sensor'), ('ADMINISTRADOR', 'Administrador'), ('FUNCIONARIO', 'Funcionário')], default='CIDADAO', max_length=15, verbose_name='Origem'),
        ),
    ]
