# Generated by Django 5.0.6 on 2025-01-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_serviceorder_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightingdevice',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
