# Generated by Django 5.0.6 on 2024-12-10 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maintenance_operational_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='operational_cost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='core.operationalcost', verbose_name='Custo Operacional'),
        ),
    ]
