# Generated by Django 5.0.6 on 2024-12-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_maintenance_operational_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='cost',
        ),
    ]
